### ISSUE TITLE
TODO: cleanup #includes further

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2006]
After PR #2000 has been merged, there are still plenty of things we can do regarding #includes and headers:

* [ ] move `TakeInterrupt` out of `stats.h` so that files don't have to include the header just for it
* [ ] `sysfiles.c` includes `gapstate.h` for `STATE(Prompt)`. A low-level source file like that should not have to access `STATE`. This is another reason to refactor the way we use `readline` (roughly speaking, I don't think we should call it automatically in `syFgets`, rather we should offer an explicit function to invoke it, and teach GAP to use that explicitly; this ties in with @markuspf's work on Jupyter, io refactoring etc.)
* [ ] move `ExecStatus` out of `gap.h` to `intrprtr.h`, and stop including `gap.h` from the latter. Also, make more functions use it as their return value, turn it into an enum, remove duplication between `STATUS_QUIT` and `STATUS_CONTINUE`, turn those enum values into sequential values (instead of powers-of-two) etc.
* [x] avoid including `io.h` from `gapstate.h`
* [ ] perhaps rename the current `gap.h` resp. move its content elsewhere, and instead have that file be a list of most/all GAP `#include` statements (taken from `compiled.h`, which then could be simplified to just that one other header `gap.h`). Afterwards, kernel extensions could be changed to `#include "gap.h"` instead of `include "compiled.h"`, which arguably makes for easier to understand code
