### ISSUE TITLE
Meta: document developer (and admin) workflows on GitHub and otherwise

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3381]
We really should document far more things, for GAP developers (committers and non-committers) and also admins. This then is both useful for onboarding of new contributors; but also for existing developers, and admins. It'll make sure things can move on even if certain people with (currently) critical knowledge that nobody else has are not available.

At least three places come to mind for this kind of information:
1. `CONTRIBUTING.md` in the repository: available to everybody using GAP, also offline; but updating it requires some effort
2. One or multiple Wiki pages -- very easy to edit, but only available online
3. In one of the manuals.

Personally I'd use 1. for things that are not likely to change a lot, and 2. for the rest. E.g. `CONTRIBUTING.md` can contain general information about how we make releases; while the wiki would contain concrete dates for upcoming releases.

A list of information I think we should document:

- [ ] how the CI setup works (see #907 and #1740)
- [ ] how releases are made: @alex-konovalov already created docs for that, [see here](https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/RELEASE_CHECKLIST.md), but not everybody knows about them, so I'd add link to them in a central location
- [ ] when releases are made (at some point we said we'd like to make a new major release every 6 month, and then 1-3 minor updates in between, depending on need)
   - [ ] also list planned/expected dates for the next two or so major releases somewhere (e.g. Wiki)
- [ ] explain about GitHub labels, and how we mean to use them
   - [ ] perhaps also give a rough overview of what labels there are, and what they are for?
- [ ] explain about GitHub milestones, and how we mean to use them
- [ ] GitHub admin:
   - [ ] whom do we give commit rights, and how? For that latter: by adding them to the GitHub group "GAP committer
   - [ ] to allow people to add labels, approve PRs and more, they can be added to the "GAP contributors" group (this does allow for pushing / merging of PRs)
   - [ ] explain how "GAP contributors" works: by giving members "Write" permission for `gap-system/gap` and `gap-system/GapWWW` (TODO: extend in the future), but then taking away right to commit (and to dismiss reviews) via GitHub's "branch protection rules)

I am sure there are more things we should document. Please make suggestions below, I'll add them here as appropriate.

**Comment by ssiccha** [comment]
I'd like to keep the `CONTRIBUTING.md` focused on onboarding new contributors. ATM it contains information on how to
- report issues,
- submit PRs,
- review PRs.

We could put all other information into the `dev/` directory, and add an overview file `DEVELOPERS.md`. We can e.g. add a `RELEASE-WORKFLOW.md` to the `dev/` directory.
