### ISSUE TITLE
Complete release automation / make a release

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4281]
1. [x] import the new scripts into the GAP repository (see PR #4279)
2. [x] finish the release notes... manually, or with a script, or ... see issue #4257 and PR #4277 
2. [x] set up a GitHub Action triggered by a cron time for "nightlies", and one triggered by new tags (whether they share code or are really two fully separate actions: I don't care) (see PR #4282); @FriedrichRober and @ssiccha wrote the code for that, and I've been tweaking it a bit. I'll open a PR for it, but want to first tweak it a bit more, so 
3. [x] allow updaing manuals on the website
    - [ ] add code to extract the GAP & package manuals from a release tarball (work begun here: https://github.com/gap-system/GapWWW/pull/227)
    - [ ] Decide where/how manuals for GAP and packages are hosted in the future (see https://github.com/gap-system/GapWWW/issues/223)
    - [ ] unless we resolve the preceding point quickly, for now insert a manual step into the release intructions ("... now use the following commands to copy the files you got via method X to serve Y...")
make sure that the website updates work
4. [x] finish the rest of the website related work
5. [x] also set up GitHub Action automation on the GapWWW repository doing the above (perhaps with a manual trigger?)
6. [x] get @ChrisJefferson "new Cygwin release/installer" working, and ideally also have a GitHub Action job for this which spits out the .exe installer at the end, ready for use on the website...
6. [ ] test the whole setup...
7. [ ] make an actual release

Did I forget something? Please feel free to edit this text!

**Comment by fingolfin** [comment]
We made two releases with the system now, it works
