### ISSUE TITLE
Distributed packages without a `License` field

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4802]
... in the current package distribution snapshot (which is currently ~2 weeks old, so some of these may be already resolved). Also, for many of those, the current `git` version already has a `License` file, there just was no release since it was added (I've marked this for a few packages, but this is not comprehensive).

If people want to help resolve this:
- if you maintain any of these packages, please add the `License` field and make a new release
- anybody can also check out packages on this list, check if their git version has a `License` field: if yes, add a comment here saying so (resp. edit this text); if no, then submit an issue or PR there about it, and add the link here.

The goal should be to have a `License` field in the package meta data for all packages, and then enforce this for new packages.
- [x] `ANUPQ` -- see https://github.com/gap-packages/anupq/issues/25, released in v3.2.6
- [x] `Automata` -- released in v1.15
- [x] `CRIME` -- released in v1.6
- [x] `CRISP` -- released in v1.4.6
- [x] `FGA` -- released in v1.5.0 (from our fork of FGA)
- [x] `FinInG` -- released in v1.5
- [x] `GRAPE` -- released in v4.9.0
- [x] `GUAVA` -- released in v3.16
- [x] `ITC` -- released in v1.5.1
- [x] `JupyterViz` -- see https://github.com/nathancarter/jupyterviz/pull/11
- [x] `LiePRing` -- released in v2.6
- [x] `loops` -- released in v3.4.3
- [x] `lpres` -- released in v1.0.3
- [x] `MajoranaAlgebras` -- see https://github.com/MWhybrow92/MajoranaAlgebras/pull/46
- [x] `MapClass` -- released in v1.4.5
- [x] `NoCK` -- see https://github.com/pjastr/NoCK/pull/7
- [x] `PatternClass` -- already in git, [needs a release](https://github.com/gap-packages/PatternClass/issues/23)
- [x] `permut` -- already in git, [needs a release](https://github.com/gap-packages/permut/issues/23)
- [x] `RadiRoot` -- released in v2.9
- [x] `SglPPow` -- released in v2.2
- [x] `SgpViz` -- released in v0.999.5
- [x] `SONATA` -- released in v2.9.2
- [x] `Sophus` -- released in v1.25
- [x] `StandardFF` -- see <s>https://github.com/frankluebeck/StandardFF/pull/4</s> https://github.com/frankluebeck/StandardFF/commit/30b69c784de95d1b7fc39cd3b5aae892e4a81f6a, awaiting release of version 0.9.5, see also https://github.com/frankluebeck/StandardFF/issues/5
- [x] `Thelma` -- released in v1.3
- [x] `TransGrp` -- see https://github.com/hulpke/transgrp/pull/45
- [x] `Unipot` -- released in v1.5
- [x] `UnitLib` --  released in 4.1.0
- [x] `uuid` -- released in v0.7

The following GAP code was used to produce the list above:
```gap
pis:=GAPInfo.PackagesInfo;;
nolicense:=Filtered(RecNames(pis),n->not ForAny(pis.(n),p->IsBound(p.License)));
for n in SortedList(nolicense) do
  Print("- [ ] `",pis.(n)[1].PackageName,"`\n");
od;
```

**Comment by fingolfin** [comment]
Last package now has a license, yay!
