### ISSUE TITLE
Get rid of SuPeRfail

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#560]
This is a meta-issue to keep track of the process of getting rid of `SuPeRfail` (if you don't know what this is: good!) The plan is do it this way:
- [x] Provide an alternative to the only GAP API using it.  See #488: `READ_COMMAND_REAL` can now be used instead of `READ_COMMAND`; the latter is now just a thin wrapper around the former.
- [x] Remove any other uses of `SuPeRfail`  in the GAP kernel and library. See #488
- [x] Make a GAP release with these changes. Available in GAP 4.8.2
- [x] Identify packages using it and get them to change. Specifically, these are:
  - [X] `CAP`: homalg-project/homalg_project#151
  - [x] `io`: see gap-packages/io#42
  - [x] `openmath`: https://github.com/gap-packages/openmath/issues/1
  - [X] `rcwa`: was removed in version 3.7.0
  - [x] `scscp`: https://github.com/gap-packages/scscp/pull/4
  - [x] `sgpviz`: just needs to be changed to use `READ_COMMAND_REAL` instead of `READ_COMMAND`
  - [X] `ToolsForHomalg`: homalg-project/homalg_project#151

**Comment by alex-konovalov** [comment]
SCSCP package done by @fingolfin (thanks). I will check the box when the new version will be released and picked up.

**Comment by alex-konovalov** [comment]
I've resolved this in OpenMath package too. Will check the box when the new version will be released and picked up. 

Thus, only `sgpviz` remains...

**Comment by alex-konovalov** [comment]
New releases of OpenMath and SCSCP picked up. Still no SgpViz release since 2008. Has anybody contacted authors?

**Comment by fingolfin** [comment]
I emailed Manuel Delgado today.

**Comment by alex-konovalov** [comment]
This may now be closed, as we have merged #1374
