### ISSUE TITLE
Meta: issue and pull request template

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#645]
https://github.com/blog/2111-issue-and-pull-request-templates explains how to make templates for issues and pull requests. I think it will be very useful to establish them. They could contain some reminders and checklists that could help to remind to add tests, document changes for the next release, check whether the branch for the PR is most appropriate etc. Nothing long, otherwise nobody will read it, and also would be fine to start from the template and throw the full text away and write something completely different.

What about the following:

* Issue template:

Please make sure that you specified
- [ ] Operating system
- [ ] Version of GAP and, if necessary, GAP packages involved in the issue
- [ ] Information sufficient to reproduce the issue

* PR template

Please make sure that before submitting this pull request you have checked all of the following:
- [ ] the branch into which this pull request should go is selected accordingly to these guidelines (link to wiki)
- [ ] the test files for this change are contained in GAP already or included in the PT
- [ ] the changes that should be mentioned in the release overview are described on (this wiki page)
